---
clusters:
    - name: ch-test-host
      host: clickhouse-server
      port: 9000
      user: $CH_USER
      pass: $CH_PASS
      sources:
        - git-repo: git@github.com:orginux/sql-cd-test.git
          git-branch: main
          git-paths:
            - queries/common
